s3 {
    endpoint = "https://s3.eu-west-2.amazonaws.com/"
    multipart.part.size.bytes = 8388608
    multipart.part.size.bytes = ${?S3_MULTIPART_PART_SIZE_BYTES}
}

s3files.mount.point = "/mnt/s3"
s3files.large.file.threshold.bytes = 524288000
s3files.large.file.threshold.bytes = ${?S3FILES_LARGE_FILE_THRESHOLD_BYTES}

checksum.buffer.size.bytes = 8388608
checksum.buffer.size.bytes = ${?CHECKSUM_BUFFER_SIZE_BYTES}

poll_malware_scan_complete.await.secs = 5
droid.signature.name="DROID_SignatureFile_V"
containers.signature.name="container-signature-"

droid.version="124"
containers.version="20260119"
