
root.directory="/tmp"
s3 {
    endpoint = "https://s3.eu-west-2.amazonaws.com/"
}

chunk {
    size = 100
    size = ${?CHUNK_SIZE_IN_MB}
}

signatures {
  cdn = "https://cdn.nationalarchives.gov.uk/documents"
  nationalArchivesUrl = "https://www.nationalarchives.gov.uk"
}

droid.signature.name="DROID_SignatureFile_V"
containers.signature.name="container-signature-"

droid.version="122"
containers.version="20260119"
